### ISSUE TITLE
Permission to use your code for my master thesis software program

### ISSUE THREAD

**Issue by vanecardenas** [sciecode/sciecode.github.io#10]
Hello Mr. Avila,

My name is Vanessa and I am a student from Peru. Currently developing my master thesis program which is in short, drawing medical lesions on a 3D head model.

I found an example for texture painting in threeJs that you did some time ago:
https://rawcdn.githack.com/sciecode/three.js/f4e363a8e0cf6c496f4191192d7eb15110442a7c/examples/webgl_paint_texture.html 

I wanted to ask you if I could use some parts of your code and make some adaptations because I can see that with your code I can make my program work in a smoother way. I would cite you in my thesis for the used code from the example.

Thanks for your time in advance.

Best regards,
Vanessa

**Comment by sciecode** [comment]
Hey Vanessa,

Absolutely, please feel free to use & modify the code in whichever way you need. I believe the version you linked worked mainly with a HTML5 canvas for the brushing step. I developed a different version entirely on WebGL, but unfortunately I lost that one. I'll let you know if I manage to find it.

Aside from that, feel free to hit me up if you need any help. I'm provide any help needed.

Good luck on your thesis.
